server:
  servlet:
    context-path: /logviewer
###############################################
#
# authentication
#
spring:
  security:
    user:
      name: usertoset
      password: pwtoset
  mvc:
    servlet:
      path: /
      
###############################################
#
# log folder
#

configuration:
  folder: /opt/smgwa/ess

###############################################
# logging
logging:
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

  level:
    de:
      swm: INFO

